import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/fonts/inter";
import { QueryProvider } from "@/components/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} antialiased`}>
      <body className="min-h-screen w-full">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
